#################################################
# Install rbenv and ruby

- name: "Install mongodb and dependencies"
  apt: pkg={{ item }} state=latest
  with_items:
    - mongodb-10gen
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev

- name: "Install mongodb"
  remote_user: "{{ user }}"
  sudo: false
  git: repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_home }}

- name: "Install ruby-build"
  remote_user: "{{ user }}"
  sudo: false
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{ rbenv_home }}/plugins/ruby-build

- name: "Add `~/.rbenv/bin` to your $PATH for access to the rbenv command-line utility."
  remote_user: "{{ user }}"
  sudo: false
  lineinfile: dest={{ user_home }}/.bash_profile
              backup=yes
              create=yes
              state=present
              line='export PATH="$HOME/.rbenv/bin:$PATH"'

- name: "Add rbenv init to shell to enable shims and autocompletion."
  remote_user: "{{ user }}"
  sudo: false
  lineinfile: dest={{ user_home }}/.bash_profile
              backup=yes
              create=yes
              state=present
              line='eval "$(rbenv init -)"'

- name: "Install ruby"
  remote_user: "{{ user }}"
  sudo: false
  action: shell CONFIGURE_OPTS=--disable-install-doc {{ rbenv_cmd }} install {{ ruby_version }} creates={{ rbenv_home }}/versions/{{ ruby_version }}

# Needed so the gem commands operate on the right ruby - might be a better way of doing this
- name: "Set global ruby"
  remote_user: "{{ user }}"
  sudo: false
  action: shell {{ rbenv_cmd }} global {{ ruby_version }}

- name: "Install bundler"
  remote_user: "{{ user }}"
  sudo: false
  action: shell {{ rbenv_env }} gem install bundler --no-rdoc --no-ri

- name: "Rehash rbenv"
  remote_user: "{{ user }}"
  sudo: false
  action: shell {{ rbenv_cmd }} rehash

# end of rbenv and ruby instalation
#################################################