#################################################
# Install mongodb

- name: "Import the public key used by the package management system"
  shell: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"

- name: "Create a list file for MongoDB"
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: update aptitude
  apt: update_cache=yes

- name: "Install mongodb and dependencies"
  apt: pkg={{ item }} state=latest
  with_items:
    - mongodb-org
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev

#################################################