---
- name: Install nginx
  apt: pkg=nginx state=latest

- name: Start nginx at boot
  service: name=nginx enabled=yes

- name: Copy nginx configuration for site
  template: >
    src={{ server_hostname }}.conf
    dest=/etc/nginx/sites-available/{{ server_hostname }}.conf
    owner=root group=root
  notify: restart nginx

- name: Symlink site in sites-enabled
  file: >
    src=/etc/nginx/sites-available/{{ server_hostname }}.conf
    dest=/etc/nginx/sites-enabled/{{ server_hostname }}.conf
    owner=root group=root state=link
  notify: restart nginx